# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Projects\Python\MlApp\UI\coefsWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(734, 415)
        self.btClose = QtWidgets.QPushButton(Dialog)
        self.btClose.setGeometry(QtCore.QRect(580, 350, 131, 41))
        self.btClose.setObjectName("btClose")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 30, 691, 291))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame1 = QtWidgets.QFrame(self.widget)
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame1)
        self.label.setMaximumSize(QtCore.QSize(225, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.coefsTable = QtWidgets.QTableWidget(self.frame1)
        self.coefsTable.setObjectName("coefsTable")
        self.coefsTable.setColumnCount(0)
        self.coefsTable.setRowCount(0)
        self.verticalLayout.addWidget(self.coefsTable)
        self.verticalLayout_2.addWidget(self.frame1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(225, 16777215))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Коэффициенты и смещения"))
        self.btClose.setText(_translate("Dialog", "Закрыть"))
        self.label.setText(_translate("Dialog", "Коэффициенты:"))
        self.label_2.setText(_translate("Dialog", "Смещения"))
