# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Projects\Python\MlApp\UI\patientEditWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 540)
        Dialog.setMinimumSize(QtCore.QSize(520, 540))
        Dialog.setMaximumSize(QtCore.QSize(520, 540))
        Dialog.setStyleSheet("font: 10pt \"Trebuchet MS\";")
        self.btAccept = QtWidgets.QPushButton(Dialog)
        self.btAccept.setGeometry(QtCore.QRect(180, 470, 161, 51))
        self.btAccept.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    font-size: 11pt;\n"
"    background-color: transparent;\n"
"    border: 2px solid rgb(38, 86, 131);\n"
"    transition: all 1s ease-out;\n"
"    color: rgb(38, 86, 131);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(38, 86, 131);\n"
"color: white;\n"
"}\n"
"")
        self.btAccept.setObjectName("btAccept")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(120, 10, 281, 51))
        self.label_5.setStyleSheet("font: 16pt \"Century Gothic\";")
        self.label_5.setObjectName("label_5")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 100, 481, 331))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.editLastName = QtWidgets.QLineEdit(self.widget)
        self.editLastName.setText("")
        self.editLastName.setObjectName("editLastName")
        self.verticalLayout.addWidget(self.editLastName)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.editName = QtWidgets.QLineEdit(self.widget)
        self.editName.setText("")
        self.editName.setObjectName("editName")
        self.verticalLayout.addWidget(self.editName)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.editMidName = QtWidgets.QLineEdit(self.widget)
        self.editMidName.setText("")
        self.editMidName.setObjectName("editMidName")
        self.verticalLayout.addWidget(self.editMidName)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.cmDoctors = QtWidgets.QComboBox(self.widget)
        self.cmDoctors.setObjectName("cmDoctors")
        self.verticalLayout.addWidget(self.cmDoctors)
        self.btSwitchToData = QtWidgets.QPushButton(self.widget)
        self.btSwitchToData.setMinimumSize(QtCore.QSize(0, 50))
        self.btSwitchToData.setStyleSheet("margin-top: 10px;\n"
"")
        self.btSwitchToData.setCheckable(False)
        self.btSwitchToData.setObjectName("btSwitchToData")
        self.verticalLayout.addWidget(self.btSwitchToData)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btAccept.setText(_translate("Dialog", "Применить"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Добавление записи</p></body></html>"))
        self.label.setText(_translate("Dialog", "Фамилия"))
        self.label_2.setText(_translate("Dialog", "Имя"))
        self.label_3.setText(_translate("Dialog", "Отчество"))
        self.label_4.setText(_translate("Dialog", "Доктор"))
        self.btSwitchToData.setText(_translate("Dialog", "Данные..."))
