# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/patientVerdictWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 350)
        self.bt_accept = QtWidgets.QPushButton(Dialog)
        self.bt_accept.setGeometry(QtCore.QRect(220, 290, 141, 41))
        self.bt_accept.setObjectName("bt_accept")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 30, 521, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_state = QtWidgets.QLabel(self.widget)
        self.lb_state.setStyleSheet("font-size: 20pt;")
        self.lb_state.setObjectName("lb_state")
        self.verticalLayout.addWidget(self.lb_state)
        self.lb_recs = QtWidgets.QLabel(self.widget)
        self.lb_recs.setStyleSheet("font-size: 16pt;")
        self.lb_recs.setObjectName("lb_recs")
        self.verticalLayout.addWidget(self.lb_recs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_state_2 = QtWidgets.QLabel(self.widget)
        self.lb_state_2.setStyleSheet("font-size: 16pt;")
        self.lb_state_2.setObjectName("lb_state_2")
        self.horizontalLayout.addWidget(self.lb_state_2)
        self.lb_acc = QtWidgets.QLabel(self.widget)
        self.lb_acc.setStyleSheet("font-size: 16pt;")
        self.lb_acc.setObjectName("lb_acc")
        self.horizontalLayout.addWidget(self.lb_acc)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Вердикт"))
        self.bt_accept.setText(_translate("Dialog", "Принять"))
        self.lb_state.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">TextLabel</span></p></body></html>"))
        self.lb_recs.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.lb_state_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Оценка точности:</p></body></html>"))
        self.lb_acc.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">acc</span></p></body></html>"))
