# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Projects\Python\MlApp\UI\startWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        MainWindow.setStyleSheet("font: 9pt \"Trebuchet MS\";\n"
"background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 70, 451, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("margin: 0 auto;")
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.loginText = QtWidgets.QLineEdit(self.frame)
        self.loginText.setMinimumSize(QtCore.QSize(0, 25))
        self.loginText.setMaximumSize(QtCore.QSize(400, 25))
        self.loginText.setObjectName("loginText")
        self.verticalLayout.addWidget(self.loginText)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.passwordText = QtWidgets.QLineEdit(self.frame)
        self.passwordText.setMaximumSize(QtCore.QSize(400, 25))
        self.passwordText.setInputMask("")
        self.passwordText.setObjectName("passwordText")
        self.verticalLayout.addWidget(self.passwordText)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 290, 141, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 4px;\n"
"background-color: rgb(69, 72, 255);\n"
"color: white;\n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(49, 51, 182);\n"
"cursor:pointer;\n"
"}\n"
"QPushButton:disabled{\n"
"color: rgb(72, 72, 72);\n"
"background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 30, 291, 51))
        self.label_4.setStyleSheet("font: 15pt \"Century Gothic\";\n"
"text-align: center;\n"
"background-color: none;")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Аутентификация"))
        self.label_2.setText(_translate("MainWindow", "Логин"))
        self.label.setText(_translate("MainWindow", "Пароль"))
        self.pushButton.setText(_translate("MainWindow", "Войти"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Введите логин и пароль</p></body></html>"))
